
language: node_js

node_js:
    - lts/*

install:
    - npm install
    - npm install -g typescript
    - npm install -g codeclimate-test-reporter

script:
    - yarn build
    - yarn test
    - yarn run test:coverage

after_script:
    codeclimate-test-reporter < coverage/lcov.info
